### ISSUE TITLE
`Archive.commit()` might be blocked, when two or more archive looking the same path

### ISSUE THREAD

**Issue by jongwon-jay-lee** [monologg/ko_lm_dataformat#10]
## 🐛 Bug Report

동일 디렉토리에 대해서 archive 를 두번이상 선언할 경우,
current_chunk_incomplete 에 대해서  2개 이상의 프로세스가 점유하고 있어,
이후 rename이 되지 않음

## 🔬 How To Reproduce

```
>>> from tests.testing_utils import TMP_DIR_NAME, get_tests_dir, remove_tmp_dir
>>> archive = kldf.Archive(TMP_DIR_NAME)
>>> text = open(get_tests_dir(append_path="./tests/assets/kowiki_sample.txt"), "r", encoding="utf-8").read()
>>> text
'제임스 얼 "지미" 카터 주니어(, 1924년 10월 1일 ~ )는 민주당 출신 미국 39대 대통령 (1977년 ~ 1981년)이다. 지미 카터는 조지아주 섬터 카운티 플레인스 마을에서 태어났다. 조지아 공과대학교를 졸업하였다. 그 후 해군에 들어가 전함·원자력
·잠수함의 승무원으로 일하였다. 1953년 미국 해군 대위로 예편하였고 이후 땅콩·면화 등을 가꿔 많은 돈을 벌었다.\n대한민국 제16대 대통령 선거는 2002년 12월 19일 목요일 한국의 새로운 대통령을 뽑기 위한 선거로 치러졌다. 16대 대선은 지난
 15대 대선에서 간발의 차로 낙선하고 재도전한 이회창 한나라당 후보와 사상 최초의 국민 참여 경선을 통해 여당의 대통령 후보가 된 노무현 새천년민주당 후보의 양강 구도로 진행되었다. 대선 재수생인 이회창 후보는 경험이나 세력 면에서 노무현
 후보보다 대권 고지에 좀 더 유리할 것으로 점쳐졌으나, 이전 대선부터 불거진 이회창 후보의 두 아들의 병역기피 논란, 노사모를 비롯한 네티즌들의 열성적인 노무현 지지, 정몽준 후보와의 단일화 성공 등에 힘입어 노무현 후보가 당선되었다. 만
20세 이상의 대한민국 국민은 선거권이 있었다. 즉, 1982년 12월 19일 이전에 태어난 사람은 투표를 할 자격이 있었다.\n함석헌(咸錫憲, 1901년 3월 13일 ~ 1989년 2월 4일)은 대한민국의 독립운동가, 종교인, 언론인, 출판인이며 기독교운동가, 시민
사회운동가였다. 광복 이후 비폭력 인권 운동을 전개한 민권운동가이자 언론인, 재야운동가, 문필가 활약한 그의 본관은 강릉(江陵)이며 호는 신천(信天), 씨알, 바보새이다. 1919년 3.1 운동에 참여했다가 퇴학 당한 후, 사무원과 소학교 교사 등을
전전하다가 1928년부터 1938년까지 오산학교의 교사를 역임했다.'
>>> archive.add_data(text, split_sent=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Github\ko_lm_dataformat\ko_lm_dataformat\archive.py", line 53, in add_data
    assert self.sentence_splitter
AssertionError
>>> archive = kldf.Archive(TMP_DIR_NAME, sentence_splitter=kldf.KssSentenceSplitter())
>>> archive.add_data(text, split_sent=True)
>>> archive.commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Github\ko_lm_dataformat\ko_lm_dataformat\archive.py", line 79, in commit
    os.rename(os.path.join(self.out_dir, "current_chunk_incomplete"), fname)
PermissionError: [WinError 32] 다른 프로세스가 파일을 사용 중이기 때문에 프로세스가 액세스 할 수 없습니다: 'tmp_dir\\current_chunk_incomplete' -> 'tmp_dir/data_0_210709105957_v0.1.0_default.jsonl.zst'
```

### Environment

* OS: Windows 
* Python version, get it with: 3.7

```bash
python --version
```

## 📈 Expected behavior

1. The latest `archive` obj declared should get the permission of editing `current_chunk_incomplete`
2. Create a new file instead of rename

**Comment by jongwon-jay-lee** [comment]
[PR#15](https://github.com/monologg/ko_lm_dataformat/pull/15)를 통해 issue resolve 후 close합니다.
